---
image: docker:stable-dind

services:
  - docker:dind

before_script:
  - apk add --no-cache
    python3 python3-dev py3-pip gcc git curl build-base
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssh sudo
  - docker info
  - python3 --version
  - python3 -m pip install ansible==2.9 ansible-lint==4.3 molecule[docker] molecule[lint]
  - ssh-keygen -f /root/.ssh/id_rsa -t rsa -N ''
  - ansible --version
  - molecule --version

molecule:
  stage: test
  script:
    - molecule test
