- hosts: all
  become: true
  tasks:
          - name: add users
            user:
                    name: ansible
                    groups: wheel 
                    append: yes
                    system: yes
                    state: present
                    create_home: true
          - name: copy ssh key to ansible user
            authorized_key:
                    user: ansible
                    state: present
                    key: "{{ lookup('file', '/home/avremy/.ssh/id_rsa.pub') }}"
