- name: set tmp file name
  set_fact:
          tmp_file: /tmp/passwords-{{ ansible_date_time.iso8601 }}
  run_once: true
- file:
    path: "{{ tmp_file }}"
    state: touch
#  delegate_to: 127.0.0.1
  run_once: true

- lineinfile:
    path: "{{ tmp_file }}"
    line: url,username,password,extra,name,group,fav
 #  delegate_to: 127.0.0.1
  run_once: true

- name: create password and add to csv
  lineinfile:
    path: "{{ tmp_file }}"
    line: "{{ inventory_hostname }},{{ username }},{{ my_pass }},,,backend,0"
# delegate_to: 127.0.0.1

