---
# tasks file for basesetup
- name: create password file
  import_tasks: create-password-tempfile.yml
  delegate_to: 127.0.0.1

- name: create user and password save data to "{{ tmp_file }}"
  import_tasks: password.yml

- name: install base software Redhat
  import_tasks: update-install-base-centos.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: install base software arch 
  import_tasks: update-install-base-arch.yml
  when: ansible_facts['os_family'] == "Archlinux"

- name: install ohmyzsh
  include_role:
    name: gantsign.oh-my-zsh
  vars:
          become_user: "{{ username }}"
          users:
                  - username: "{{ username }}"

- name: install powerline_shell
  import_tasks: powerline_shell.yml
